on: [push, pull_request]

name: Package

env:
  APP_NAME: virtualfolder

jobs:
  package:
    name: Package nightly release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup krankler
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.1/krankerl
          chmod +x krankerl
      - name: Package app
        run: ./krankerl package
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}.tar.gz
          path: build/artifacts/${{ env.APP_NAME }}.tar.gz
